/*
YSL javascript library
*/

(function(){if(window.YSL){throw("YSL NAMESPACE ALREADY DEFINED");}
var Y={meta:{ver:'3.0.0',cp:'sasumi',build:'20121004'},D:document,L:location,W:window,com:{},widget:{}};Y.emptyFn=function(){};if(!Y.W.console){Y.W.console={log:Y.emptyFn,warn:Y.emptyFn,exception:Y.emptyFn,error:Y.emptyFn,info:Y.emptyFn,dir:Y.emptyFn};};Y.ready=function(fn){var cb=function(){fn(Y);};if(Y.D.readyState==="complete"){return setTimeout(cb,1);}
if(Y.D.addEventListener){Y.D.addEventListener("DOMContentLoaded",cb,false);Y.W.addEventListener("load",cb,false);}else if(Y.D.attachEvent){Y.D.attachEvent("onreadystatechange",cb);Y.W.attachEvent("onload",cb);}};Y.ENV=(function(){var ENV_DATA={};var _ABS_URL;return{getAbsUrl:function(){if(_ABS_URL){return _ABS_URL;}
var scripts=Y.D.getElementsByTagName('SCRIPT');for(var i=0;i<scripts.length;i++){if(scripts[i].src){var match=/(.*\/)(.*?\.js$)/ig.exec(scripts[i].src);if(match[1]&&/^ysl\..*js/i.test(match[2])){_ABS_URL=match[1];return _ABS_URL;}}}},setData:function(key,val){ENV_DATA[key]=val;},get:function(key){return ENV_DATA[key]},remove:function(key){delete ENV_DATA[key];}};})();Y.use=(function(){var DEF_SL;return function(moduleListStr,callback,option){callback=callback||Y.emptyFn;if(!Y.net){throw('NET MODULE REQUIRED');}
if(!DEF_SL){DEF_SL=new Y.net.ScriptLoader();}
var moduleList=[],tmpList=moduleListStr.split(',');for(var i=0;i<tmpList.length;i++){if(Y.string.trim(tmpList[i])){moduleList.push(Y.string.trim(tmpList[i]).replace(/^Y\.|^YSL\./i,''));}}
var doneCount=0;var doneCheck=function(){if(doneCount==moduleList.length){callback(Y);}};Y.lang.each(moduleList,function(module){if(Y.object.route(Y,module)){doneCount++;doneCheck(Y);}else{var fileName=module.replace(/\./g,'/').toLowerCase()+'.js';var path=Y.ENV.getAbsUrl()+fileName;DEF_SL.add(path,option);DEF_SL.loadQueue(function(){doneCount++;doneCheck(Y);});}});};})();window.YSL=Y;})();(function(Y){var _LANG={};_LANG.toArray=function(col){if(col.item){var l=col.length,arr=new Array(l);while(l--)arr[l]=col[l];return arr;}else{var arr=[];for(var i=0;i<col.length;i++){arr[i]=col[i];}
return arr;}};_LANG.inArray=function(item,arr){for(var i=arr.length-1;i>=0;i--){if(arr[i]==item){return true;}}
return false;};_LANG.isEmptyObject=function(obj){if(typeof(obj)=='object'){for(var i in obj){if(i!==undefined){return false;}}}
return true;};_LANG.isPlainObject=function(obj){return obj&&toString.call(obj)==="[object Object]"&&!obj["nodeType"]&&!obj["setInterval"];};_LANG.isScalar=function(value){var type=_LANG.getType(value);return type=='number'||type=='boolean'||type=='string'||type=='null'||type=='undefined';};_LANG.isBomOrDom=function(value){if(this.isScalar(value)){return false;}
if(Y.ua.ie){return value['nodeType']||value['srcElement']||(value['top']&&value['top']==Y.W.top);}else{return this.getType(value)!='object'&&this.getType(value)!='function';}};_LANG.isBoolean=function(obj){return this.getType(obj)=='boolean';};_LANG.isString=function(obj){return this.getType(obj)=='string';};_LANG.isArray=function(obj){return this.getType(obj)=='array';};_LANG.isFunction=function(obj){return this.getType(obj)=='function';};_LANG.getType=function(obj){return obj===null?'null':(obj===undefined?'undefined':Object.prototype.toString.call(obj).slice(8,-1).toLowerCase());};_LANG.each=function(obj,callback){var value,i=0,length=obj.length,isObj=(length===undefined)||(typeof(obj)=="function");if(isObj){for(var name in obj){if(callback.call(obj[name],obj[name],name,obj)===false){break;}}}else{for(value=obj[0];i<length&&false!==callback.call(value,value,i,obj);value=obj[++i]){}}
return obj;};_LANG.createClass=function(s,p){var t=this,sp,ns,cn,scn,c,de=0;s=/^((static) )?([\w.]+)(\s*:\s*([\w.]+))?/.exec(s);cn=s[3].match(/(^|\.)(\w+)$/i)[2];ns=t.createNS(s[3].replace(/\.\w+$/,''));if(ns[cn]){return;}
if(s[2]=='static'){ns[cn]=p;if(this.onCreate){this.onCreate(s[2],s[3],ns[cn]);}
return;}
if(!p[cn]){p[cn]=function(){};de=1;}
ns[cn]=p[cn];t.extend(ns[cn].prototype,p);if(s[5]){if(!t.resolve(s[5])){throw('ve.Class namespace parser error');}
sp=t.resolve(s[5]).prototype;scn=s[5].match(/\.(\w+)$/i)[1];c=ns[cn];if(de){ns[cn]=function(){return sp[scn].apply(this,arguments);};}else{ns[cn]=function(){this.base=sp[scn];return c.apply(this,arguments);};}
ns[cn].prototype[cn]=ns[cn];t.each(sp,function(f,n){ns[cn].prototype[n]=sp[n];});t.each(p,function(f,n){if(sp[n]){ns[cn].prototype[n]=function(){this.base=sp[n];return f.apply(this,arguments);};}else{if(n!=cn){ns[cn].prototype[n]=f;}}});}
t.each(p['static'],function(f,n){ns[cn][n]=f;});if(this.onCreate){this.onCreate(s[2],s[3],ns[cn].prototype);}};_LANG.createNS=function(n,o){var i,v;o=o||Y.W;n=n.split('.');for(i=0;i<n.length;i++){v=n[i];if(!o[v]){o[v]={};}
o=o[v];}
return o;};_LANG.resolve=function(n,o){var i,l;o=o||Y.W;n=n.split('.');for(i=0,l=n.length;i<l;i++){o=o[n[i]];if(!o){break;}}
return o;}
Y.lang=_LANG;})(YSL);(function(Y){if(Y.D.querySelector&&Y.D.querySelectorAll){Y.querySelector=function(selector,context){var dom=context||Y.D;return dom.querySelector(selector);};Y.querySelectorAll=function(selector,context){var dom=context||Y.D;return dom.querySelectorAll(selector);};return;}
var getElement=function(selector,context,cond){var result_lst=[],matches=[],context=context||Y.D,cond=cond||' ';if(typeof(selector)!=='string'){return selector;}
if(selector=='body'||selector=='head'||selector=='html'){return Y.D.getElementsByTagName(selector);}else if(selector=='window'){return[Y.W];}
selector=selector.replace(/(^\s*)|(\s*$)/g,'').replace(/\s+/ig,' ').replace(/\s*\>\s*/ig,'>');matches=selector.match(/([^\s|^\>]+)|([\s|\>]+)/ig);if(matches.length==1&&matches[0].charAt(0)=='#'){return[Y.D.getElementById(matches[0].substring(1))];}
else if(matches.length==1){var context_lst=context.nodeType?[context]:context;var tmp=[],tmp2=[],att=null,pseudo=null,node_tags=matches[0].match(/^\w+/ig),node_tag=node_tags?node_tags[0]:null;for(var i=0;i<context_lst.length;i++){var sub_result_lst=[];if(cond=='>'){Y.lang.each(context_lst[i].childNodes,function(node){node_tag?(node.nodeName.toLowerCase()==node_tag&&sub_result_lst.push(node)):sub_result_lst.push(node);});}
else{sub_result_lst=node_tag?Y.lang.toArray(context_lst[i].getElementsByTagName(node_tag)):sub_result_lst=sub_result_lst.concat(Y.lang.toArray(context_lst[i].getElementsByTagName('*')));}
if(tmp=matches[0].match(/\.([A-Za-z0-9_-]+)/i)){tmp2=[];Y.lang.each(sub_result_lst,function(itm,idx){('  '+itm.className+' ').indexOf(' '+tmp[1]+' ')>0&&tmp2.push(itm);});sub_result_lst=tmp2;}
if(att=matches[0].match(/\[(.*?)\=(.*?)\]/i)){tmp2=[];Y.lang.each(sub_result_lst,function(itm){(itm.getAttribute(att[1])==(att[2].replace(/\'/ig,'')))&&tmp2.push(itm);});sub_result_lst=tmp2;}
if(pseudo=matches[0].match(/\:(text|textarea|radio|checkbox|password|submit|reset)/i)){tmp2=[];Y.lang.each(sub_result_lst,function(itm){(itm.type==pseudo[1])&&tmp2.push(itm);});sub_result_lst=tmp2;sub_result_lst=tmp2;}
result_lst=result_lst.concat(sub_result_lst);}
if(pseudo=matches[0].match(/\:(first|last|even|odd)/i)){switch(pseudo[1]){case'first':result_lst=[result_lst[0]];break;case'last':result_lst=[result_lst.pop()];break;case'even':tmp2=[];Y.lang.each(result_lst,function(itm,idx){idx%2&&tmp2.push(itm);});result_lst=tmp2;break;case'odd':tmp2=[];Y.lang.each(result_lst,function(itm,idx){idx%2||tmp2.push(itm);});result_lst=tmp2;break;}}}
else{for(var i=0;i<matches.length;i++){if(matches[i]!=' '&&matches[i]!='>'){if(i==0){var _m=matches;result_lst=getElement(matches[i]);matches=_m;}else{if(!result_lst){return null;}
var _m=matches;result_lst=getElement(matches[i],result_lst,matches[i-1]);matches=_m;}}}}
return result_lst;};Y.querySelector=function(){var arr=getElement.apply(null,arguments)[0];return arr;};Y.querySelectorAll=function(){return getElement.apply(null,arguments);}})(YSL);(function(Y){var _eventListDictionary={};var _objSeqUID=0;var _fnSeqUID=0;var _Event={KEYS:{F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,SHIFT:16,CTRL:17,ALT:18,BACKSPACE:8,TAB:9,RETURN:13,ESC:27,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40,DELETE:46},add:function(obj,eventType,fn,argArray){var cfn,res=false,l,obj=obj.getDomNode?obj.getDomNode():obj;if(!obj){return res;}
if(!obj.eventsListUID){obj.eventsListUID="e"+(++_objSeqUID);}
if(!(l=_eventListDictionary[obj.eventsListUID])){l=_eventListDictionary[obj.eventsListUID]={};}
if(!fn.__elUID){fn.__elUID="e"+(++_fnSeqUID)+obj.eventsListUID;}
if(!l[eventType]){l[eventType]={};}
if(typeof(l[eventType][fn.__elUID])=='function'){return false;}
cfn=function(evt){var a=fn.apply(Y.dom.one(obj),!argArray?[_Event.get(evt)]:([_Event.get(evt)]).concat(argArray));return a;};if(obj.addEventListener){obj.addEventListener(eventType,cfn,false);res=true;}else if(obj.attachEvent){res=obj.attachEvent("on"+eventType,cfn);}else{res=false;}
if(res){l[eventType][fn.__elUID]=cfn;}
return res;},addShortcut:function(obj,keys,fn,eventTypes){var ko={};Y.lang.each(keys.toLowerCase().split('+'),function(k){if(k.toCharCode())
ko[k]=true;});var eventTypes=eventTypes||['keypress'];Y.lang.each(eventTypes,function(et){_Event.add(obj,et,function(ev){if(ko){v.toUpperCase().charCodeAt(0);}});});},remove:function(obj,eventType,fn){var cfn=fn,res=false,l=_eventListDictionary,r;if(!obj){return res;}
if(!fn){return this.purge(obj,eventType);}
if(obj.eventsListUID&&l[obj.eventsListUID]){l=l[obj.eventsListUID][eventType];if(l&&l[fn.__elUID]){cfn=l[fn.__elUID];r=l;}}
if(obj.removeEventListener){obj.removeEventListener(eventType,cfn,false);res=true;}else if(obj.detachEvent){obj.detachEvent("on"+eventType,cfn);res=true;}else{return false;}
if(res&&r&&r[fn.__elUID]){delete r[fn.__elUID];}
return res;},purge:function(obj,type){var l;if(obj.eventsListUID&&(l=_eventListDictionary[obj.eventsListUID])&&l[type]){for(var k in l[type]){if(obj.removeEventListener){obj.removeEventListener(type,l[type][k],false);}else if(obj.detachEvent){obj.detachEvent('on'+type,l[type][k]);}}}
if(obj['on'+type]){obj['on'+type]=null;}
if(l){l[type]=null;delete l[type];}
return true;},get:function(evt){var evt=Y.W.event||evt,c,cnt;if(!evt&&Y.W.Event){c=arguments.callee;cnt=0;while(c){if((evt=c.arguments[0])&&typeof(evt.srcElement)!="undefined"){break;}else if(cnt>9){break;}
c=c.caller;++cnt;}}
return evt;},getButton:function(evt){var e=this.get(evt);if(!e){return-1}
if(Y.ua.ie){return e.button-Math.ceil(e.button/2);}else{return e.button;}},getTarget:function(evt){var e=this.get(evt);if(e){return e.srcElement||e.target;}else{return null;}},getCurrentTarget:function(evt){var e=this.get(evt);if(e){return e.currentTarget||Y.D.activeElement;}else{return null;}},cancelBubble:function(evt){evt=this.get(evt);if(!evt){return false}
if(evt.stopPropagation){evt.stopPropagation();}else{if(!evt.cancelBubble){evt.cancelBubble=true;}}},preventDefault:function(evt){evt=_Event.get(evt);if(!evt){return false}
if(evt.preventDefault){evt.preventDefault();}else{evt.returnValue=false;}},mousePos:function(evt){evt=this.get(evt);var x=evt.pageX||(evt.clientX+(Y.D.documentElement.scrollLeft||Y.D.body.scrollLeft));var y=evt.pageY||(evt.clientY+(Y.D.documentElement.scrollTop||Y.D.body.scrollTop));return{'x':x,'y':y};},getRelatedTarget:function(ev){ev=this.get(ev);var t=ev.relatedTarget;if(!t){if(ev.type=="mouseout"){t=ev.toElement;}else if(ev.type=="mouseover"){t=ev.fromElement;}}
return Y.dom.one(t);},delegate:function(pDom,hook,evStr,handler){var _this=this;var pDom=pDom||document.body;var hookFn=typeof(hook)=='string'?function(n){return n.nodeType==1&&n.tagName==hook.toUpperCase();}:hook;this.add(pDom,evStr,function(evt){var n=_this.getTarget(evt);while(n){if(hookFn(n)){handler.call(n,evt);return;}
n=n.parentNode;}})}}
Y.event=_Event;})(YSL);(function(Y){Y.dom={};Y.dom.getScroll=function(){return{top:Math.max(Y.D.documentElement.scrollTop,Y.D.body.scrollTop),left:Math.max(Y.D.documentElement.scrollLeft,Y.D.body.scrollLeft),height:Math.max(Y.D.documentElement.scrollHeight,Y.D.body.scrollHeight),width:Math.max(Y.D.documentElement.scrollWidth,Y.D.body.scrollWidth)};}
Y.dom.insertStyleSheet=function(rules,styleSheetID){styleSheetID=styleSheetID||'css_'+Math.random();var node=Y.dom.one('#'+styleSheetID);if(!node){node=Y.dom.one('head').create('style').setAttr({id:styleSheetID,type:'text/css'});}
node=node.getDomNode();if(node.styleSheet){node.styleSheet.cssText=rules;}else{node.appendChild(Y.D.createTextNode(rules));}
return node;};Y.dom.getWindowRegion=function(){var info={};info.screenLeft=Y.W.screenLeft?Y.W.screenLeft:Y.W.screenX;info.screenTop=Y.W.screenTop?Y.W.screenTop:Y.W.screenY;if(Y.W.innerWidth){info.visibleWidth=Y.W.innerWidth;info.visibleHeight=Y.W.innerHeight;info.horizenScroll=Y.W.pageXOffset;info.verticalScroll=Y.W.pageYOffset;}else{var tag=(Y.D.documentElement&&Y.D.documentElement.clientWidth)?Y.D.documentElement:Y.D.body;info.visibleWidth=tag.clientWidth;info.visibleHeight=tag.clientHeight;info.horizenScroll=tag.scrollLeft;info.verticalScroll=tag.scrollTop;}
var tag=(Y.D.documentElement&&Y.D.documentElement.scrollWidth)?Y.D.documentElement:Y.D.body;info.documentWidth=Math.max(tag.scrollWidth,info.visibleWidth);info.documentHeight=Math.max(tag.scrollHeight,info.visibleHeight);return info;}
function _DOM(node){this._node=node;}
_DOM.prototype.getDomNode=function(){return this._node;}
_DOM.prototype.setDomNode=function(node){this._node=node;}
_DOM.prototype.addClass=function(cls){this.getDomNode().className+=!this.existClass(cls)?(' '+cls):'';return this;}
_DOM.prototype.existClass=function(cls){var e=new RegExp('(\\s|^)'+cls+'(\\s|$)').test(this.getDomNode().className);return e;}
_DOM.prototype.removeClass=function(cls){if(this.existClass(cls)){var reg=new RegExp('(\\s|^)'+cls+'(\\s|$)');this.getDomNode().className=this.getDomNode().className.replace(reg,' ');}
return this;}
_DOM.prototype.toggleClass=function(cls1,cls2){if(this.existClass(cls1)){this.removeClass(cls1).addClass(cls2);return true;}else{this.addClass(cls1).removeClass(cls2);return false;}}
_DOM.prototype.getHtml=function(){return this.getDomNode().innerHTML;}
_DOM.prototype.setHtml=function(s){this.getDomNode().innerHTML=s;return this;}
_DOM.prototype.getValue=function(){return this.getDomNode().value||null;}
_DOM.prototype.setValue=function(val){this.getDomNode().value=val;return this;}
_DOM.prototype.getAttr=function(a){return this.getDomNode().getAttribute(a);}
_DOM.prototype.setAttr=function(a,v){if(typeof(a)=='string'){this.getDomNode().setAttribute(a,v);}else{for(var i in a){this.getDomNode().setAttribute(i,a[i]);}}
return this;}
_DOM.prototype.getStyle=function(name){if(!this.isDomNode(this.getDomNode())){return null;}
var convertName={'float':Y.W.getComputedStyle?'cssFloat':'styleFloat'},node=this.getDomNode(),name=convertName[name]||name;if(Y.W.getComputedStyle){var cs=Y.W.getComputedStyle(node,null),value=node.style[name]||cs[name];if(value===undefined&&(name=='backgroundPositionX'||name=='backgroundPositionY')){value=node.style['backgroundPosition']||cs['backgroundPosition'];value=value.split(' ')[+(name.slice(-1)=='Y')];}
return value;}else{var rOpacity=/opacity=([^)]*)/,value=node.style[name]||node.currentStyle[name],m;if(value===undefined&&name=='opacity'){value=(m=rOpacity.exec(node.currentStyle.filter))?parseFloat(m[1])/100:1;}
return value;}}
_DOM.prototype.setStyle=function(props,value){var tmp,node=this.getDomNode(),bRtn=true,w3cMode=(tmp=Y.D.defaultView)&&tmp.getComputedStyle,rexclude=/z-?index|font-?weight|opacity|zoom|line-?height/i;if(typeof(props)=='string'){tmp=props;props={};props[tmp]=value;}
for(var prop in props){value=props[prop];if(prop=='float'){prop=w3cMode?"cssFloat":"styleFloat";}else if(prop=='opacity'){value=value>=1?(value/100):value;if(!w3cMode){prop='filter';value='alpha(opacity='+Math.round(value*100)+')';}}else if(prop=='backgroundPositionX'||prop=='backgroundPositionY'){tmp=prop.slice(-1)=='X'?'Y':'X';if(w3cMode){var v=this.getStyle('backgroundPosition'+tmp);prop='backgroundPosition';typeof(value)=='number'&&(value=value+'px');value=tmp=='Y'?(value+" "+(v||"top")):((v||'left')+" "+value);}}
if(typeof node.style[prop]!="undefined"){try{node.style[prop]=value+(typeof value==="number"&&!rexclude.test(prop)?'px':'');bRtn=bRtn&&true;}catch(ex){}}else{bRtn=bRtn&&false;}}
return bRtn;}
_DOM.prototype.removeStyle=function(key){var cssText=this.getDomNode().style.cssText;if(cssText&&new RegExp('(\\s|^)'+key+'(\\s|:)','i').test(cssText)){var reg=new RegExp('(\\s|^)'+key+'[\\s]*:(.*?)(;|$)','ig');this.getDomNode().style.cssText=cssText.replace(reg,' ');}
return this;};_DOM.prototype.checkIsVisibile=function(){}
_DOM.prototype.show=function(){this.getDomNode().style.display='block';return this;}
_DOM.prototype.hide=function(){this.getDomNode().style.display='none';return this;}
_DOM.prototype.toggle=function(){this.getDomNode().style.display=this.getDomNode().style.display=='none'?'':'none';return this;}
_DOM.prototype.swap=function(tag){var tag=Y.dom.one(tag).getDomNode();if(this.getDomNode().swapNode){this.getDomNode().swapNode(tag);}else{var prt=tag.parentNode,next=tag.nextSibling;if(next==this.getDomNode()){prt.insertBefore(this.getDomNode(),tag);}else if(tag==this.nextSibling){prt.insertBefore(tag,this.getDomNode());}else{this.parentNode.replaceChild(tag,this.getDomNode());prt.insertBefore(this.getDomNode(),next);}}}
_DOM.prototype.remove=function(keepChild){var n=this.getDomNode(),p=n.parentNode;if(keepChild&&n.hasChildNodes()){while(c=n.firstChild){p.insertBefore(c,n)}}
p.removeChild(n);this.setDomNode();}
_DOM.prototype.removeAllChildren=function(){var n=this.getDomNode();while(n.hasChildNodes()){n.removeChild(n.lastChild);}};_DOM.prototype.parent=function(mix){var fn;if(typeof(mix)=='string'){fn=function(n){return n.tagName.toLowerCase()==mix.toLowerCase();};}else if(mix){fn=mix;}else{return new _DOM(Y.getDomNode().parentNode);}
var result;var p=this.getDomNode().parentNode;if(fn){while(p&&p.parentNode){if(fn(p)){return new _DOM(p);}
p=p.parentNode;}}else{return new _DOM(p);}};_DOM.prototype.getDoc=function(){var n=this.getDomNode();if(!n){return Y.D;}
return Y.ua.ie?n['document']:n['ownerDocument'];};_DOM.prototype.getWin=function(doc){if(!doc){doc=this.getDoc();}
return doc.parentWindow||doc.defaultView;};_DOM.prototype.getPosition=function(){var top=0,left=0,node=this.getDomNode();if(Y.D.documentElement.getBoundingClientRect&&node.getBoundingClientRect){var box=node.getBoundingClientRect(),oDoc=node.ownerDocument,_fix=Y.ua.ie?2:0;top=box.top-_fix+Y.dom.getScroll().top;left=box.left-_fix+Y.dom.getScroll().left;}
else{while(node.offsetParent){top+=node.offsetTop;left+=node.offsetLeft;node=node.offsetParent;}}
return{'left':left,'top':top};}
_DOM.prototype.getSize=function(){var _fix=[0,0],_this=this;Y.lang.each(['Left','Right','Top','Bottom'],function(v){_fix[v=='Left'||v=='Right'?0:1]+=(parseInt(_this.getStyle('border'+v+'Width'),10)||0)+
(parseInt(_this.getStyle('padding'+v),10)||0);});var _w=this.getDomNode().offsetWidth-_fix[0],_h=this.getDomNode().offsetHeight-_fix[1];return{width:_w,height:_h};}
_DOM.prototype.getRegion=function(){var pos=this.getPosition(),size=this.getSize();return{left:pos.left,top:pos.top,width:size.width,height:size.height}}
_DOM.prototype.setRelatePosition=function(el,pos){var curR=this.getRegion(),tagR=el.getRegion();var posArr={'center':{top:(tagR.top+tagR.height/2-curR.height/2),left:(tagR.left+tagR.width/2-curR.width/2)},'inner-left-top':{top:tagR.top,left:tagR.left},'inner-left-middle':{top:(tagR.top+tagR.height/2-curR.height/2),left:tagR.left},'inner-left-bottom':{top:(tagR.top+tagR.height-curR.height),left:tagR.left},'inner-right-bottom':{top:(tagR.top+tagR.height-curR.height),left:(tagR.left+tagR.width-curR.width)},'inner-right-middle':{top:(tagR.top+tagR.height/2-curR.height/2),left:(tagR.left+tagR.width-curR.width)},'inner-right-top':{top:tagR.top,left:(tagR.left+tagR.width-curR.width)},'inner-top-middle':{top:tagR.top,left:(tagR.left+tagR.width/2-curR.width/2)},'inner-bottom-middle':{top:(tagR.top+tagR.height-curR.height),left:(tagR.left+tagR.width/2-curR.width/2)},'outer-left-top':{top:tagR.top,left:(tagR.left-curR.width)},'outer-left-middle':{top:(tagR.top+tagR.height/2-curR.height/2),left:(tagR.left-curR.width)},'outer-left-bottom':{top:(tagR.top+tagR.height-curR.height),left:(tagR.left-curR.width)},'outer-right-bottom':{top:(tagR.top+tagR.height-curR.height),left:(tagR.left+tagR.width)},'outer-right-middle':{top:(tagR.top+tagR.height/2-curR.height/2),left:(tagR.left+tagR.width)},'outer-right-top':{top:tagR.top,left:(tagR.left+tagR.width)},'outer-top-left':{top:(tagR.top-curR.height),left:tagR.left},'outer-top-middle':{top:(tagR.top-curR.height),left:(tagR.left+tagR.width/2-curR.width/2)},'outer-top-right':{top:(tagR.top-curR.height),left:(tagR.left+tagR.width-curR.width)},'outer-bottom-left':{top:(tagR.top+tagR.height),left:tagR.left},'outer-bottom-middle':{top:(tagR.top+tagR.height),left:(tagR.left+tagR.width/2-curR.width/2)},'outer-bottom-right':{top:(tagR.top+tagR.height),left:(tagR.left+tagR.width-curR.width)},'outer-coner-left-top':{top:(tagR.top-curR.height),left:(tagR.left-curR.width)},'outer-coner-right-top':{top:(tagR.top-curR.height),left:(tagR.left+tagR.width)},'outer-coner-left-bottom':{top:(tagR.top+tagR.height),left:(tagR.left-curR.width)},'outer-coner-right-bottom':{top:(tagR.top+tagR.height),left:(tagR.left+tagR.width)}};return this.setStyle({position:'absolute',display:'block',top:posArr[pos].top,left:posArr[pos].left});};_DOM.prototype.create=function(tp,pos){var p=(this.getDomNode()||Y.D.body);p=p.nodeType==9?p=p.body:p;pos=(pos===undefined)?-1:parseInt(pos,10);var n=typeof(tp)=='string'?Y.D.createElement(tp):tp;pos==-1?p.appendChild(n):p.insertBefore(n,p.childNodes[pos]);return new _DOM(n);}
_DOM.prototype.getChildren=function(idx){var nodes=[],cns=this.getDomNode().childNodes;for(var i=cns.length-1;i>=0;i--){if(cns[i].nodeName!='#text'&&cns[i].nodeName!='#comment'){nodes.unshift(new _DOM(cns[i]));}}
return idx!==undefined?nodes[idx]:nodes;}
_DOM.prototype.searchChain=function(prop,func){prop=prop||'parentNode';var ele=this.getDomNode();while(ele){if(func.call(this,this)){return this;}
ele=ele[prop];}
return null;}
_DOM.prototype.isDomNode=function(node){return!!node.nodeType;}
_DOM.prototype.contains=function(b){var a=this.getDomNode(),b=b.getDomNode?b.getDomNode():b;return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16);}
_DOM.prototype.one=function(selector,context,cond){var context=context||this.getDomNode();if(typeof(selector)!=='string'){return selector.getOneDomNode?selector.getOneDomNode():(selector.getDomNode?selector:new _DOM(selector));}
var selector=Y.querySelector(selector,context,cond);return selector?new _DOM(selector):null;};_DOM.prototype.all=function(selector,context,cond){if(typeof(selector)!=='string'){return selector.getOneDomNode?selector:(selector.getDomNode?new _DOMCollection([selector.getDomNode()]):new _DOM(selector));}
var context=context||this.getDomNode();var result=Y.querySelectorAll(selector,context,cond);return new _DOMCollection(result);};var eventMapHash={'addEvent':'add','removeEvent':'remove','on':'add','delegate':'delegate'};for(var i in eventMapHash){(function(){var evMethod=eventMapHash[i];_DOM.prototype[i]=function(){var _tmpNode=this.getDomNode();var args=Y.lang.toArray(arguments);args.splice(0,0,_tmpNode);return Y.event[evMethod].apply(Y.event,args);}})();};function _DOMCollection(domArray){this._nodes=domArray;}
_DOMCollection.prototype.each=function(fn){Y.lang.each(this._nodes,function(item,idx,col){return fn.call(null,new _DOM(item),idx,col);});};_DOMCollection.prototype.toArray=function(){var ret=[];Y.lang.each(this._nodes,function(item){ret.push(new _DOM(item));})
return ret;};_DOMCollection.prototype.getOneDomNode=function(idx){return new _DOM(this._nodes[idx||0]);};_DOMCollection.prototype.getAllDomNodes=function(){var ret=[];Y.lang.each(this._nodes,function(item){ret.push(item);})
return ret;};Y.lang.each(_DOM.prototype,function(fn,method){_DOMCollection.prototype[method]=function(){var args=Y.lang.toArray(arguments);var ret=[];Y.lang.each(this._nodes,function(item){var _tmpNode=new _DOM(item);var r=_tmpNode[method].apply(_tmpNode,args);ret.push(r);});return ret;};});var _tmpDom=new _DOM(Y.D);var mapHash=['one','all','create','getWin','delegate'];for(var i=0;i<mapHash.length;i++){(function(){var method=mapHash[i];Y.dom[method]=function(){var args=Y.lang.toArray(arguments);return _tmpDom[method].apply(_tmpDom,args);}})();};})(YSL);(function(Y){Y.net={};var CACHE_DATA={};var setCache=function(key,data,expired){var expiredTime=(new Date()).getTime()+expired*1000;CACHE_DATA[key]={data:data,expiredTime:expiredTime};};var getCache=function(key){var time=new Date().getTime();if(CACHE_DATA[key]&&CACHE_DATA[key].expired>time){return CACHE_DATA[key].data;}else{delete CACHE_DATA[key];return null;}};Y.net.Ajax=(function(){var ajax=function(config){this.config=Y.object.extend(true,{url:null,syn:false,method:'get',data:null,format:'json',charset:'utf-8',cache:false},config);if(!this.config.url){throw('NO REQUEST URL FOUND');}
this.config.data=Y.net.buildParam(this.config.data);this.config.method=this.config.method.toLowerCase();this.config.format=this.config.format.toLowerCase();if(Y.W.XMLHttpRequest){this.xmlObj=new XMLHttpRequest();if(this.xmlObj.overrideMimeType){this.xmlObj.overrideMimeType('text/xml');}}else if(Y.W.ActiveXObject){this.xmlObj=new ActiveXObject('Msxml2.XMLHTTP')||new ActiveXObject('Microsoft.XMLHTTP');}else{throw('browser no support ajax');}};ajax.prototype.onResponse=function(response){if(!response||response.length==0){this.onError();return;}
var data=null;try{switch(this.config.format){case'json'||'javascript':eval('data = '+response.responseText+';');break;case'xml':data=response.responseXML;break;case'bool'||'boolean':data=/yes|true|y/ig.test(ret.responseText)?true:false;break;default:data=response.responseText;}}catch(ex){}
this.onResult(data);};ajax.prototype.send=function(){var _this=this;var cache_data=getCache(this.config.url);if(cache_data){this.onResponse(cache_data);return;}
this.xmlObj.onreadystatechange=function(){if(_this.xmlObj.readyState==4){if(_this.xmlObj.status==200){_this.onResponse(_this.xmlObj);setCache(_this.config.url,_this.xmlObj);}else{_this.onError(_this.xmlObj.status);}}else{if(_this.xmlObj.readyState==0){_this.onReady();}else{_this.onLoading();}}};this.xmlObj.open(this.config.method,this.config.url,!this.config.syn);if(this.config.format=='xml'){this.xmlObj.setRequestHeader('Content-Type','text/xml');}else{this.xmlObj.setRequestHeader('Content-Type','application/x-www-form-urlencoded;charset='+this.config.charset);}
if(this.config.method=='GET'){param=null;}
this.xmlObj.send(this.config.data);if(this.config.syn&&this.xmlObj&&this.xmlObj.status==200){return this.callback(this.xmlObj);}};ajax.prototype.onLoading=function(){};ajax.prototype.onResult=function(){};ajax.prototype.onError=function(){};ajax.prototype.onReady=function(){};ajax.prototype.onTimeout=function(){};return ajax;})();Y.net.flashSender=(function(){var GUID=0;var FLASHSENDER_ID='';var FLASHSENDER_OBJ='';var FLASHSENDER_SRC='';var FLASHSENDER_READY;var FLASHSENDER_INIT_CALLBACK_METHOD='FLASHSENDER_INIT_CALLBACK';var FLASHSENDER_CALLBACK_METHOD='FLASHSENDER_CALLBACK';var FLASHSENDER_CALLBACK_LIST={};Y.W[FLASHSENDER_INIT_CALLBACK_METHOD]=function(){FLASHSENDER_READY=true;delete(Y.W[FLASHSENDER_INIT_CALLBACK_METHOD]);};Y.W[FLASHSENDER_CALLBACK_METHOD]=function(params){if(!params||!params.guid||!params.data){console.log('FLAHSSENDER ERROR',params);return;}
if(FLASHSENDER_CALLBACK_LIST[params.guid]){FLASHSENDER_CALLBACK_LIST[params.guid](params.data);delete(FLASHSENDER_CALLBACK_LIST[params.guid]);}};var sender=function(config){this.config=Y.object.extend(true,{url:'',method:'get',data:{},cache:false,format:'json',guid:++GUID},config);};sender.initialize=function(){if(FLASHSENDER_READY){return;}else{Y.use('media',function(){});}};sender.prototype.onResponse=function(data){};sender.prototype.send=function(){};return sender;})();Y.net.loadCss=function(url,callback,doc){setTimeout(function(){doc=doc||Y.D;callback=callback||YSL.emptyFn;var css=doc.createElement('link');css.rel='stylesheet';css.type='text/css';css.href=url;doc.getElementsByTagName('head')[0].appendChild(css);css.onreadystatechange=css.onload=callback();},0);};(function(net){var ScriptLoader=function(){this.queue=[];this.lookup={};this.callbackList=[];this.leftCount=0;};ScriptLoader.prototype={load:function(url,callback,conf){var sc;conf=Y.object.extend({cache:1,charset:'utf-8',window:Y.W},conf||{});function done(){callback&&callback(url);if(sc.removeNode){sc.removeNode(true)}else{head.removeChild(sc);}};sc=conf.window.document.createElement('script');sc.setAttribute('charset',conf['charset']);sc.src=url;sc.onreadystatechange=sc.onload=function(){if(!sc.readyState||sc.readyState=="loaded"||sc.readyState=="complete"){done();}};var head=conf.window.document.getElementsByTagName('head')[0]||conf.window.document.body
head.appendChild(sc);},loadQueue:function(onAllDone){var t=this;if(onAllDone){this.callbackList.push(onAllDone);}
if(t.queue.length>0){var q=t.queue.shift();t.load(q.url,function(){t.leftCount--;setTimeout(function(){if(t.leftCount>0){t.loadQueue();}else{var cb;while(cb=t.callbackList.pop()){cb();}}},0);},q.option);return;}},add:function(url,option){if(this.lookup[url]){return;}
this.lookup[url]=url;this.queue.push({'url':url,'option':option});this.leftCount++;},addQueue:function(urlList){var _this=this;Y.lang.each(urlList,function(url){_this.add(url);});}};Y.net.ScriptLoader=ScriptLoader;var _scl=new ScriptLoader();Y.net.loadScript=_scl.load;})(Y.net);(function(net){var GUID=0;var DataGetter=function(config){var _this=this;this.config=Y.object.extend(true,{url:null,callbacker:'DataGetterCallback'+(GUID++)},config);Y.W[this.config.callbacker]=function(data){if(!data){_this.onError();}else{_this.onResponse(data);}
Y.W[_this.config.callbacker]=null;if(_this.tmpScriptNode){_this.tmpScriptNode.parentNode.removeChild(_this.tmpScriptNode);}};if(!this.config.url){throw('DATA GETTER PARAM ERROR');}
this.config.url+=(this.config.url.indexOf('?')>0?'&':'?')+'callback='+this.config.callbacker;};DataGetter.prototype.send=function(){this.tmpScriptNode=Y.net.loadScript(this.config.url,function(){},this.config);};DataGetter.prototype.onError=function(){};DataGetter.prototype.onResponse=function(){};net.DataGetter=DataGetter;net.loadData=function(url,callback){var config={url:url};var gd=new DataGetter(config);gd.onResponse=callback||Y.emptyFn;gd.send();};})(Y.net);Y.net.buildParam=function(){var fixType=function(val){return typeof(val)=='string'||typeof(val)=='number';};var data=[];Y.lang.each(arguments,function(params){if(Y.lang.isArray(params)){Y.lang.each(params,function(item){if(fixType(item)){data.push(item);}});}else if(typeof(params)=='object'){for(var i in params){if(fixType(params[i])){data.push(i+'='+params[i]);}}}else{return params;}});return data.join('&');};Y.net.mergeRequest=function(url){var params=Y.lang.toArray(arguments);if(params.length<2){throw('params count illegle');}
var str=Y.net.buildParam(params.slice(1));var url=params[0];return url+(url.indexOf('?')>=0?'&':'?')+str;};Y.net.getParameter=function(param,url){var r=new RegExp("(\\?|#|&)"+param+"=([^&#]*)(&|#|$)");var m=(url||location.href).match(r);return(!m?"":m[2]);}})(YSL);(function(Y){var uas=Y.W.navigator.userAgent.toLowerCase();var b={ie:!!Y.W.ActiveXObject,opera:!!Y.W.opera&&Y.W.opera.version,webkit:uas.indexOf(' applewebkit/')>-1,air:uas.indexOf(' adobeair/')>-1,quirks:Y.D.compatMode=='BackCompat',safari:/webkit/.test(uas)&&!/chrome/.test(uas),firefox:/firefox/.test(uas),chrome:/chrome/.test(uas),userAgent:uas};var k='';for(var i in b){if(b[i]){k='safari'==i?'version':i;break;}}
b.ver=k&&RegExp("(?:"+k+")[\\/: ]([\\d.]+)").test(uas)?RegExp.$1:"0";b.ver=b.ie?parseInt(b.ver,10):b.ver;if(b.ie){b.ie8Compat=Y.D.documentMode==8;b.ie7Compat=(b.ie==7&&!Y.D.documentMode)||Y.D.documentMode==7;b.ie6Compat=b.ie<7&&b.quirks;}
if(b.ie&&b.ver==9){b.ver=Y.D.addEventListener?9:8;}
if(b.ie){b['ie'+b.ver]=true;}
b.isIE=function(v){return b.ie==v;};Y.ua=b;})(YSL);(function(Y){var PROTOTYPE_FIELDS=['constructor','hasOwnProperty','isPrototypeOf','propertyIsEnumerable','toLocaleString','toString','prototype','valueOf'];var _Object={bind:function(obj,fn){var slice=Array.prototype.slice;var args=slice.call(arguments,2);return function(){var _obj=obj||this,_args=args.concat(slice.call(arguments,0));if(typeof(fn)=='string'){if(_obj[fn]){return _obj[fn].apply(_obj,_args);}}else{return fn.apply(_obj,_args);}};},route:function(obj,path){obj=obj||{};path=String(path);var r=/([\d\w_]+)/g,m;r.lastIndex=0;while((m=r.exec(path))!==null){obj=obj[m[0]];if(obj===undefined||obj===null){break;}}
return obj;},extend:function(){if(arguments.length<2){throw('params error');}
var args=Y.lang.toArray(arguments),result,deepCopy=false;if(Y.lang.getType(args[0])=='boolean'){deepCopy=args[0];args=args.slice(1);}
result=args.pop();for(var i=args.length-1;i>=0;i--){var current=args[i];var _tagType=Y.lang.getType(result);if(_tagType=='null'||_tagType=='undefined'){result=current;continue;}
if(Y.lang.isScalar(result)||Y.lang.isBomOrDom(result)){continue;}
for(var key in result){var item=result[key];if(deepCopy&&typeof(item)=='object'){current[key]=this.extend(false,item);}else{current[key]=item;}}
for(var j=0;j<PROTOTYPE_FIELDS.length;j++){key=PROTOTYPE_FIELDS[j];if(Object.prototype.hasOwnProperty.call(result,key)){current[key]=result[key];}}
result=current;}
return result;}};Y.object=_Object;})(YSL);(function(Y){var _String={}
_String.str2asc=function(str){return str.charCodeAt(0).toString(16);};_String.repeat=function(str,n){if(n>1){return new Array(n+1).join(str);}
return str;};_String.trim=function(str,charlist){var whitespace,l=0,i=0;str+='';if(!charlist){whitespace=" \n\r\t\f\x0b\xa0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u3000";}else{charlist+='';whitespace=charlist.replace(/([\[\]\(\)\.\?\/\*\{\}\+\$\^\:])/g,'$1');}
l=str.length;for(i=0;i<l;i++){if(whitespace.indexOf(str.charAt(i))===-1){str=str.substring(i);break;}}
l=str.length;for(i=l-1;i>=0;i--){if(whitespace.indexOf(str.charAt(i))===-1){str=str.substring(0,i+1);break;}}
return whitespace.indexOf(str.charAt(0))===-1?str:'';};_String.parseRequestStringToObjParam=function(str){if(typeof(str)!='string'||!str){return str;}
var data={},tmp,list=str.split('&');for(var i=0,len=list.length;i<len;++i){tmp=list[i].split('=');data[tmp[0]]=tmp[1];}
return data;};_String.removeUbb=function(s){s=s.replace(/\[em\]e(\d{1,3})\[\/em\]/g,"");s=s.replace(/\[(img)\].*\[\/img\]/ig,"");s=s.replace(/\[(flash)\].*\[\/flash\]/ig,"");s=s.replace(/\[(video)\].*\[\/video\]/ig,"");s=s.replace(/\[(audio)\].*\[\/audio\]/ig,"");s=s.replace(/&nbsp;/g,"");s=s.replace(/\[\/?(b|url|img|flash|video|audio|ftc|ffg|fts|ft|email|center|u|i|marque|m|r|quote)[^\]]*\]/ig,"");return s;};_String.asc2str=function(str){return String.fromCharCode(str);};_String.ansiEncode=function(str){var ret='',strSpecial="!\"#$%&’()*+,/:;<=>?[]^`{|}~%",tt="";for(var i=0;i<str.length;i++){var chr=str.charAt(i);var c=_String.str2asc(chr);tt+=chr+":"+c+"n";if(parseInt("0x"+c)>0x7f){ret+="%"+c.slice(0,2)+"%"+c.slice(-2);}else{if(chr==" "){ret+="+";}else{ret+=(strSpecial.indexOf(chr)!=-1)?("%"+c.toString(16)):chr;}}}
return ret;}
_String.ansiDecode=function(str){var ret="";for(var i=0;i<str.length;i++){var chr=str.charAt(i);if(chr=="+"){ret+=" ";}else if(chr=="%"){var asc=str.substring(i+1,i+3);if(parseInt("0x"+asc)>0x7f){ret+=_String.asc2str(parseInt("0x"+asc+str.substring(i+4,i+6)));i+=5;}else{ret+=_String.asc2str(parseInt("0x"+asc));i+=2;}}else{ret+=chr;}}
return ret;}
Y.string=_String;})(YSL);(function(Y){var _Cookie={create:function(key,val,h){if(h){var date=new Date();date.setTime(date.getTime()+(h*60*60*1000));var expires="; expires="+date.toGMTString();}else{var expires='';}
Y.D.cookie=key+"="+val+expires+"; path=/";},read:function(key){var n=key+'=';var ca=Y.D.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1,c.length);}
if(c.indexOf(n)==0){return c.substring(n.length,c.length);}}
return null;},remove:function(key){this.create(key,'',-1);}};Y.com.cookie=_Cookie;})(YSL);(function(Y){var _Date={parse:function(tag){var res=data={},def={Y:0,m:1,d:1,H:0,i:0,s:0};if(typeof(tag)!='string'){return Y.extend(tag,def);}
tag=tag.replace(/(^\s*)|(\s*$)/g,'');if(res=tag.match(/(\d{4})\D*(\d{1,2})\D*(\d{1,2})\s*(\d{1,2})\D*(\d{1,2})\D*(\d{1,2})/)){data={Y:res[1],m:res[2],d:res[3],H:res[4],i:res[5],s:res[6]};}
else if(res=tag.match(/(\d{4})\D*(\d{1,2})\D*(\d{1,2})/)){data={Y:res[1],m:res[2],d:res[3]};}
else if(res=tag.match(/(\d{1,2})\D*(\d{1,2})\D*(\d{4})\s*(\d{1,2})\D*(\d{1,2})\D*(\d{1,2})/)){data={Y:res[3],m:res[1],d:res[2],H:res[4],i:res[5],s:res[6]};}
else{return null;}
data=Y.extend(data,def);Y.lang.each(data,function(item,i){data[i]=parseInt(item,10);});return data;},today:function(){var D=new Date();return{Y:D.getFullYear(),m:D.getMonth()+1,d:D.getDate(),H:D.getHours(),i:D.getMinutes(),s:D.getSeconds()};},format:function(objDate,fmt){return'';},offset:function(end_date,start_date){start_date=start_date||this.today();d2=this.parse(end_date);d1=this.parse(start_date);var s_d=new Date(d1.Y,d1.m-1,d1.d,d1.H,d1.i,d1.s),e_d=new Date(d2.Y,d2.m-1,d2.d,d2.H,d2.i,d2.s),RT={};var offset=(e_d.getTime()-s_d.getTime());if(offset<0){return{Y:0,m:0,d:0,H:0,i:0,s:0};}
RT.Y=Math.floor(offset/(86400*365000));RT.m=Math.floor((offset-86400*365000*RT.Y)/(86400*30000));RT.d=Math.floor((offset-86400*365000*RT.Y-86400*30000*RT.m)/(86400000));RT.H=Math.floor((offset-86400*365000*RT.Y-86400*30000*RT.m-86400000*RT.d)/(3600000));RT.i=Math.floor((offset-86400*365000*RT.Y-86400*30000*RT.m-86400000*RT.d-3600000*RT.H)/(60000));RT.s=Math.floor((offset-86400*365000*RT.Y-86400*30000*RT.m-86400000*RT.d-3600000*RT.H-RT.i*60000)/1000);return RT;}};Y.com.date=_Date;})(YSL);(function(Y){var FLASH_VERSION;var _Media={getFlashVersion:function(){if(!FLASH_VERSION){var resv=0;if(navigator.plugins&&navigator.mimeTypes.length){var x=navigator.plugins['Shockwave Flash'];if(x&&x.description){resv=x.description.replace(/(?:[a-z]|[A-Z]|\s)+/,"").replace(/(?:\s+r|\s+b[0-9]+)/,".").split(".");}}else{try{for(var i=(resv=6),axo=new Object();axo!=null;++i){axo=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+i);resv=i;}}catch(e){if(resv==6){resv=0;}
resv=Math.max(resv-1,0);}
try{resv=new QZFL.media.SWFVersion(axo.GetVariable("$version").split(" ")[1].split(","));}catch(ignore){}}
if(!(resv instanceof QZFL.media.SWFVersion)){resv=new QZFL.media.SWFVersion(resv);}
if(resv.major<3){resv.major=0;}
FLASH_VERSION=resv;}
return FLASH_VERSION;},getFlashHtml:function(flashArgs,requiredMajorVersion,cid){var _attrs=[],_params=[];for(var k in flashArgs){switch(k){case"noSrc":case"movie":continue;break;case"id":case"name":case"width":case"height":case"style":if(typeof(flashArgs[k])!='undefined'){_attrs.push(' ',k,'="',flashArgs[k],'"');}
break;case"src":if(Y.ua.ie){_params.push('<param name="movie" value="',(flashArgs.noSrc?"":flashArgs[k]),'"/>');}else{_attrs.push(' data="',(flashArgs.noSrc?"":flashArgs[k]),'"');}
break;default:_params.push('<param name="',k,'" value="',flashArgs[k],'" />');}}
if(Y.ua.ie){_attrs.push(' classid="clsid:',cid||'D27CDB6E-AE6D-11cf-96B8-444553540000','"');}else{_attrs.push(' type="application/x-shockwave-flash"');}
if(requiredMajorVersion){_attrs.push(' codeBase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab#version=',requiredMajorVersion,'"');}
return"<object"+_attrs.join("")+">"+_params.join("")+"</object>";},insertFlash:function(container,option){container=Y.dom.one(container).getDomNode();option=Y.object.extend(true,{src:'',width:'100%',height:'100%',noSrc:true},option);container.innerHTML=_Media.getFlashHtml(option);var f=container.firstChild;if(Y.ua.ie){setTimeout(function(){f.LoadMovie(0,option.src);},0);}else{f.setAttribute("data",option.src);}},getWMMHtml:function(wmpArgs,cid){var params=[],objArgm=[];for(var k in wmpArgs){switch(k){case"id":case"width":case"height":case"style":case"src":objArgm.push(' ',k,'="',wmpArgs[k],'"');break;default:objArgm.push(' ',k,'="',wmpArgs[k],'"');params.push('<param name="',k,'" value="',wmpArgs[k],'" />');}}
if(wmpArgs["src"]){params.push('<param name="URL" value="',wmpArgs["src"],'" />');}
if(Y.ua.ie){return'<object classid="'+(cid||"clsid:6BF52A52-394A-11D3-B153-00C04F79FAA6")+'" '+objArgm.join("")+'>'+params.join("")+'</object>';}else{return'<embed '+objArgm.join("")+'></embed>';}}};Y.com.media=_Media;})(YSL);YSL.use('widget.Tween',function(Y){var SUPPORT_PROS_REG=/^(left|top|right|bottom|width|height|margin|padding|spacing|backgroundx|backgroundy)$/i;var STEP_FREQ={'veryslow':8,'slow':2,'normal':1,'fast':0.5,'veryfast':0.25};var Animate=function(tag,config){var _this=this;this.target=Y.dom.one(tag);this.config=Y.object.extend(true,{interval:15,tween:'Elastic.easeOut',from:{},to:{},speed:'veryslow',step:null},config);this.status=0;this._t=0;this._timer;this.onStart=this.onRuning=this.onPause=this.onResume=this.onFinish=Y.emptyFn;this.config.speed=this.config.speed.toLowerCase();if(Y.lang.isString(this.config.tween)){this.config.tween=Y.object.route(Y.widget.Tween,this.config.tween);}
if(typeof(this.config.tween)!='function'||!this.target){throw('PARAM ERROR IN ANIMATE');}
Y.lang.each(this.config.to,function(val,key){if(SUPPORT_PROS_REG.test(key)){_this.config.from[key]=parseInt(_this.target.getStyle(key),10);if(!_this.config.step){var f=Math.abs(Math.ceil((_this.config.to[key]-_this.config.from[key])/_this.config.interval));_this.config.step=Math.ceil(f*STEP_FREQ[_this.config.speed]);}}});};Animate.prototype._run=function(){var _this=this;var b,c,d=this.config.step;var _run=function(){if(_this.status==1){var newStyle={};Y.lang.each(_this.config.to,function(item,key){c=item-_this.config.from[key];newStyle[key]=_this.config.tween(_this._t,_this.config.from[key],c,d);});_this.target.setStyle(newStyle);if(_this._t++<d){_this.onRuning(_this._t);_this._timer=setTimeout(_run,_this.config.interval);}else{_this.onFinish();_this.status=3;}}};_run();};Animate.prototype.start=function(){this.onStart();this.reset();this.status=1;this._run();};Animate.prototype.reset=function(){this.status=0;this._t=0;clearTimeout(this._timer);this.target.setStyle(this.config.from);};Animate.prototype.stop=function(){this.reset();};Animate.prototype.pause=function(){if(this.status==1){this.status=2;this.onPause();}};Animate.prototype.resume=function(){if(this.status==2){this.status=1;this._run();this.onResume();}};Y.widget.Animate=Animate;});(function(Y){var DatePicker=function(config){this.config={showLunaCalendar:true,showTimePicker:false,showWeekColumn:false,yearRange:'1980-2050',dayLang:'Sun,Mon,Thr,Wen,Thu,Fri,Sat',monthLang:'January,February,March,April,May,June,July,August,September,October,November,December',weekLang:'Wk',sid:'_date_picker_sid_'+Math.random(),cssClass:{today:'today',lastMonthDate:'last_month_date',nextMonthDate:'next_month_date',sunday:'sunday',saturday:'saturday',dateSelected:'selected',initDate:'init_date'},cssStyle:[''].join(''),template:[''].join(''),formInput:null};this.panel=null;this.initDateObj={};this.dateInfo={y:1970,m:1,d:1,h:00,i:00,s:00};this.parseDateVal=function(str){var dobj=str?new Date(str):new Date();var dateObj={y:dobj.getFullYear(),m:dobj.getMonth()+1,d:dobj.getDate(),h:dobj.getHours(),i:dobj.getMinutes(),s:dobj.getSeconds()};return dateObj;};this.appendStyleSheet=function(){};this.getDateHash=function(dateObj){var dateStar=(new Date(dateObj.y,dateObj.m-1,1)).getDay();var dateNum=(new Date(dateObj.y,dateObj.m,0)).getDate();var lastMonthDateNum=(new Date(dateObj.y,dateObj.m-1,0)).getDate();var maxCellNum=42;var dateHash=[];for(var i=0;i<maxCellNum;i++){var hashInfo={};if(i<dateStar){hashInfo={y:(dateObj.m==1?dateObj.y-1:dateObj.y),m:(dateObj.m==1?12:(dateObj.m-1)),d:lastMonthDateNum-(dateStar-i)+1};}else if(i<dateNum+dateStar){hashInfo={y:dateObj.y,m:dateObj.m,d:i-dateStar+1};}else{hashInfo={y:dateObj.m==12?dateObj.y+1:dateObj.y,m:(dateObj.m==12?1:(dateObj.m+1)),d:i-(dateNum+dateStar)+1}}
dateHash.push(hashInfo);}
return dateHash;};this.createPanel=function(){this.panel=Y.dom.one('#datepicker_01');this.panel.setStyle({width:this.config.showWeekColumn?200:176});var dayStr=this.config.dayLang.split(',').join('</span></li><li><span>');var html='';if(this.config.showWeekColumn){html='<li><span>'+this.config.weekLang+'</span></li>';}
html+='<li><span>'+dayStr+'</span></li>';this.getPanelEl('.datepicker_daylist').setHtml(html);if(this.config.showTimePicker){var timepicker_html='<select size="1">';for(var i=1;i<=23;i++){timepicker_html+='<option value="'+i+'">'+i+'</option>';}
timepicker_html+='</select>时';timepicker_html+='<select size="1">';for(var i=1;i<=60;i++){timepicker_html+='<option value="'+i+'">'+i+'</option>';}
timepicker_html+='</select>分';timepicker_html+='<select size="1">';for(var i=1;i<=60;i++){timepicker_html+='<option value="'+i+'">'+i+'</option>';}
timepicker_html+='</select>秒';timepicker_html+='<input type="button" value="确定"/>';this.getPanelEl('.datepicker_timepicker').setHtml(timepicker_html);}
this.bindPanelEvent();};this.onDateSelect=function(){};this.getPanel=function(){return this.panel;};this.adjustPanelPos=function(ele){var region=ele.getRegion();this.panel.setStyle({left:region.left,top:region.top+region.height+4});};this.bindFormInput=function(input){var SID_KEY='_date_picker_sid_';var _this=this;DatePicker.INSTANCES[this.config.sid]=this;input.setAttr(SID_KEY,this.config.sid);input.on('focus',function(){_this.initDateObj=_this.parseDateVal(this.value);_this.show(null,this);});this.onDateSelect=function(dateStr){input.setValue(dateStr);_this.hide();};Y.dom.one(document).on('click',function(){if(!_this.panel){return;}
var tag=Y.event.getTarget();var sid=tag.getAttribute(SID_KEY);if(sid!=_this.config.sid&&!_this.panel.contains(tag)){_this.hide();}});};this.show=function(dateStr,ele){var ele=ele||this.config.formInput;ele=Y.dom.one(ele||document.body);if(!this.panel){this.createPanel();}
this.adjustPanelPos(ele);var dateInfo={};if(ele.getDomNode().tagName=='INPUT'&&ele.getDomNode().value){dateInfo=this.parseDateVal(ele.getDomNode().value);}else{dateInfo=this.parseDateVal(dateStr);}
this.jumpToDate(dateInfo);this.panel.show();};this.hide=function(){this.panel.hide();};this.getPanelEl=function(selector){var result=Y.dom.getEl(selector,this.panel.getDomNode());if(result.getNode){return result;}else{return result[0];}};this.jumpToNextMonth=function(){if(this.dateInfo.m==12){this.dateInfo.y++;this.dateInfo.m=1;}else{this.dateInfo.m++;}
this.jumpToDate(this.dateInfo);};this.jumpToPrevMonth=function(){if(this.dateInfo.m==1){this.dateInfo.y--;this.dateInfo.m=12;}else{this.dateInfo.m--;}
this.jumpToDate(this.dateInfo);};this.formatDate=function(dateObj,format){format=format||'yyyy-mm-dd';var Y=dateObj.y+'',M=dateObj.m<10?'0'+dateObj.m:dateObj.m,D=dateObj.d<10?'0'+dateObj.d:dateObj.d;return format.replace('yyyy',Y).replace('yy',Y.slice(-2)).replace('mm',M).replace('m',dateObj.m).replace('dd',D).replace('d',dateObj.d);};this.jumpToDate=function(dateInfo){this.dateInfo=dateInfo;var dateHash=this.getDateHash(dateInfo);var html='';var dobj=new Date();for(var i=0;i<dateHash.length;i++){var _classList=[];var dateStr=this.formatDate(dateHash[i]);if(i<7&&dateHash[i].d>20){_classList.push(this.config.cssClass.lastMonthDate);}else if(i>20&&dateHash[i].d<15){_classList.push(this.config.cssClass.nextMonthDate);}
if(this.initDateObj.y==dateHash[i].y&&this.initDateObj.m==dateHash[i].m&&this.initDateObj.d==dateHash[i].d){_classList.push(this.config.cssClass.initDate);}
if(dateHash[i].d==dobj.getDate()&&dateHash[i].m==(dobj.getMonth()+1)&&dateHash[i].y==dobj.getFullYear()){_classList.push(this.config.cssClass.today);}
html+='<li class="'+_classList.join(' ')+'"><a href="javacript:;" rel="'+dateStr+'" title="'+dateStr+'">'+dateHash[i].d+'</a></li>';}
this.getPanelEl('ul.datepicker_datelist').setHtml(html);if(this.config.showWeekColumn){var weekHash=this.getWeekHash(dateInfo);var html='<li><span>'+weekHash.join('</span></li><li><span>')+'</span></li>';this.getPanelEl('.datepicker_weeklist').setHtml(html).show();}
var yidx='';var yr=this.config.yearRange.split('-');this.getPanelEl('*[rel=year-selector]').removeAllChildren();for(var i=yr[0];i<=yr[1];i++){this.getPanelEl('*[rel=year-selector]').getDomNode().appendChild(new Option(i,i));if(i==dateInfo.y){yidx=i-yr[0];}}
this.getPanelEl('*[rel=year-selector]').getDomNode().selectedIndex=yidx;var mt=this.config.monthLang.split(',');this.getPanelEl('*[rel=month-selector]').removeAllChildren();for(var i=1;i<=12;i++){this.getPanelEl('*[rel=month-selector]').getDomNode().appendChild(new Option(mt[i-1],i));}
this.getPanelEl('*[rel=month-selector]').getDomNode().selectedIndex=(dateInfo.m-1);};this.getWeekHash=function(dateInfo){var start=new Date(dateInfo.y,0,1);var now=new Date(dateInfo.y,dateInfo.m,1);var weekStart=Math.ceil((now.getTime()-start.getTime())/(86400*7*1000))+1;var weekHash=[];for(var i=0;i<6;i++){weekHash.push(weekStart+i-5);}
return weekHash;};this.bindPanelEvent=function(){var _this=this;this.getPanelEl('*[rel=year-selector]').on('change',function(){_this.jumpToDate({y:this.value,m:_this.dateInfo.m,d:_this.dateInfo.d});});this.getPanelEl('*[rel=month-selector]').on('change',function(){_this.jumpToDate({y:_this.dateInfo.y,m:this.value,d:_this.dateInfo.d});});this.getPanelEl('*[rel=prev-month]').on('click',function(){_this.jumpToPrevMonth();});this.getPanelEl('*[rel=next-month]').on('click',function(){_this.jumpToNextMonth();});this._lastClickDateNode=null;this.getPanelEl('ul.datepicker_datelist').on('click',function(ev){var tag=Y.event.getTarget();if(tag.tagName=='A'){if(_this._lastClickDateNode){_this._lastClickDateNode.removeClass(_this.config.cssClass.dateSelected);}
_this._lastClickDateNode=Y.dom.getEl(tag);_this._lastClickDateNode.addClass(_this.config.cssClass.dateSelected);_this.onDateSelect(tag.getAttribute('rel'));Y.event.preventDefault();return;}});var scroll=function(e){e=e||Y.W.event;var dir;if(e.wheelDelta){dir=e.wheelDelta>0?1:-1;}else if(e.detail){dir=e.detail<0?1:-1;}
_this[dir<0?'jumpToNextMonth':'jumpToPrevMonth']();};this.getPanel('ul.datepicker_datelist').on('mousewheel',scroll);this.getPanel('ul.datepicker_datelist').on('DOMMouseScroll',scroll);};if(!DatePicker.INSTANCES){DatePicker.INSTANCES=[this];DatePicker.INSTANCES_LEN=1;}else{DatePicker.INSTANCES.push(this);DatePicker.INSTANCES_LEN++;}
this.config=YSL.object.extend(this.config,config);if(this.config.formInput){this.bindFormInput(this.config.formInput);}}
DatePicker.INSTANCES=[];DatePicker.INSTANCES_LEN=0;DatePicker.hideAll=function(){for(var i in DatePicker.INSTANCES){DatePicker.INSTANCES[i].hide();}};DatePicker.autoBindFormInputDatePicker=function(){Y.event.add(Y.W,'load',function(){var inps=Y.dom.all('input[type=text]');inps.each(function(input){new DatePicker({formInput:input});});});};DatePicker.autoBindFormInputDatePicker();Y.W.DatePicker=DatePicker;})(YSL);(function(Y){var Dragdrop=function(){};Dragdrop.prototype={onDrag:function(){},onDrop:function(){}};Y.widget.Dragdrop=Dragdrop;})(YSL);(function(Y){Y.widget.helper={select:function(tp,tag){var tag=tag||Y.dom.one(Y.D);Y.dom.one(tag).all('input:checkbox').each(function(_chk){var chk=_chk.getDomNode();chk.checked=tp=='all'?true:(tp=='none'?false:!chk.checked);});},placeHolder:function(el,normalClass,focusClass,emptyClass){normalClass=normalClass||'';focusClass=focusClass||'';emptyClass=emptyClass||'';el=Y.dom.one(el);var phTxt=el.getAttr('placeholder');if(!phTxt){throw'need placeholder attr';return;}
el.on('focus',function(){el.removeClass(emptyClass);el.removeClass(normalClass);el.addClass(focusClass);if(el.getValue()==phTxt){el.setValue('');}});el.on('blur',function(){el.removeClass(emptyClass).removeClass(normalClass).removeClass(focusClass);if(el.getValue()==''||el.getValue()==phTxt){el.setValue(phTxt);el.addClass(emptyClass);}else{el.addClass(normalClass);}});}};})(YSL);YSL.use('widget.Animate',function(Y){var slide=function(id,config){config=config||{};this.ele=Y.dom.one('#'+id);this.config=Y.object.extend(false,{defaultIdx:0,speed:'normal',cssClass:{pageWrap:'Slide-page-wrap',prevBtn:'Slide-prev-btn',nextBtn:'Slide-next-btn',pageCtn:'Slide-page-ctn'}},config);this._init();};slide.prototype._init=function(){var cfg=this.config,self=this;this.pageWrap=this.ele.one('.'+cfg.cssClass.pageWrap);this.pageList=this.pageWrap.getChildren();if(this.pageList.length==0){return;}
this.maxIdx=this.pageList.length-1;var wrapWidth=0;this.posArray=[];this.pageWidthArray=[];Y.lang.each(this.pageList,function(item){var pageCtn=item.one('.'+cfg.cssClass.pageCtn);var left=pageCtn.getPosition().left;var width=pageCtn.getRegion().width;self.posArray.push(left);self.pageWidthArray.push(width);wrapWidth+=item.getRegion().width;});this.pageWrap.setStyle('width',wrapWidth);if(this.maxIdx>0){this.prevBtn=Y.dom.create('a').addClass(cfg.cssClass.prevBtn);this.nextBtn=Y.dom.create('a').addClass(cfg.cssClass.nextBtn);this.ele.getDomNode().appendChild(this.prevBtn.getDomNode());this.ele.getDomNode().appendChild(this.nextBtn.getDomNode());this._bindEvent();}
this.curIdx=cfg.defaultIdx;this.jumpTo(this.curIdx);};slide.prototype._bindEvent=function(){var self=this;this.prevBtn.on('click',function(e){Y.event.preventDefault();if(self.curIdx>0){var idx=self.curIdx-1;self.jumpTo(idx);}});this.nextBtn.on('click',function(e){Y.event.preventDefault();if(self.curIdx<self.maxIdx){var idx=self.curIdx+1;self.jumpTo(idx);}});Y.dom.one(Y.W).on('resize',function(){self.jumpTo(self.curIdx);})},slide.prototype.onJump=function(){},slide.prototype.jumpTo=function(idx,callback){if(idx<0||idx>this.maxIdx){return;}
var cfg=this.config,self=this,left,viewW=this.ele.getRegion().width,page=this.pageList[idx];pageW=page.getRegion().width,pageCtn=page.one('.'+cfg.cssClass.pageCtn),ctnLeft=this.posArray[idx],ctnW=this.pageWidthArray[idx];if(viewW>ctnW){left=(viewW-ctnW)/2-ctnLeft;}else{left=-ctnLeft;}
left=left>0?0:left;if(this.ani){this.ani.pause();}
this.ani=new YSL.Animate('#'+cfg.cssClass.pageWrap,{tween:'Quart.easeIn',speed:cfg.speed,to:{left:left}});this.ani.onFinish=function(){self.onJump(idx);self.curIdx=idx;if(self.maxIdx==0){return;}
if(self.curIdx==0){self.prevBtn.hide();}else if(self.curIdx==self.maxIdx){self.nextBtn.hide();}else{self.prevBtn.show();self.nextBtn.show();}}
this.ani.start();};Y.widget.PageSlide=slide;});(function(Y){Y.widget.Pagination=function(config){this.config=Y.object.extend({itemTotal:0,pageSize:10,pageIndex:1,numOffset:5,modelStr:'',container:null,showIfEmpty:true,cssClassName:{first:'pagination_first',next:'pagination_next',num:'pagination_num',eclipse:'pagination_eclipse',last:'pagination_last'},onPageSwitch:function(tagPageIndex,srcPageIndex){}},config);if(!this.config.container){throw"NO PAGINATION CONTAINER SPECIFYED";}else{this.config.container=Y.dom.one(this.config.container);}
this.bindEvent();};Y.widget.Pagination.prototype.bindEvent=function(){var _this=this;this.config.container.on('click',function(ev){var tag=Y.event.getTarget(ev);if(tag.tagName=='A'){switch(tag.rel){case'first':_this.jumpToPage(1);break;case'next':_this.jumpToPage(_this.config.pageIndex+1);break;case'num':_this.jumpToPage(tag.getAttribute('num'));break;}
Y.event.preventDefault();return false;}});};Y.widget.Pagination.prototype.jumpToPage=function(pageIndex){console.log('jumpToPage',pageIndex);if(this.config.pageTotal<pageIndex){pageIndex=this.config.pageTotal;}
this.config.onPageSwitch(pageIndex,this.config.pageIndex);this.config.pageIndex=pageIndex;this.show();};Y.widget.Pagination.prototype.show=function(){if(!this.config.itemTotal){return;}
this.config.pageTotal=Math.ceil(this.config.itemTotal/this.config.pageSize);var html=[];if(this.config.pageIndex>this.config.pageTotal){this.config.pageIndex=this.config.pageTotal;}
if(this.config.pageIndex>1){html.push('<a href="#page=1" class="'+this.config.cssClassName.first+'" rel="first">第一页</a>');}else{html.push('<span class="'+this.config.cssClassName.first+'">第一页</span>');}
if(this.config.pageIndex-this.config.numOffset>0){html.push('<span class="'+this.config.cssClassName.eclipse+'">...</span>');}
for(var i=this.config.pageIndex;i<=(this.config.pageIndex+this.config.numOffset);i++){if(i>0&&i<=this.config.pageTotal){html.push((this.config.pageIndex!=i)?'<a href="#page='+i+'" class="'+this.config.cssClassName.num+'" rel="num">'+i+'</a>':'<span class="'+this.config.cssClassName.num+'">'+i+'</span>');}}
if(this.config.pageIndex+this.config.numOffset<this.config.pageTotal){html.push('<span class="'+this.config.cssClassName.eclipse+'">...</span>');}
if(this.config.pageIndex<this.config.pageTotal){html.push('<a href="#page='+(this.config.pageIndex+1)+'" class="'+this.config.cssClassName.next+'" rel="next">下一页</a>');}else{html.push('<span class="'+this.config.cssClassName.next+'">下一页</span>');}
this.config.container.setHtml(html.join(''));};})(YSL);YSL.use('widget.masklayer',function(Y){Y.dom.insertStyleSheet(['.PopupDialog {position:absolute; top:20px; left:20px; width:350px; border:1px solid #999; background-color:white; box-shadow:0 0 10px #535658}','.PopupDialog-hd {height:28px; background-color:#e4e4e4; cursor:move; position:relative;}','.PopupDialog-hd h3 {font-size:12px; font-weight:bolder; color:gray; padding-left:10px; line-height:28px;}','.PopupDialog-close {display:block; overflow:hidden; width:28px; height:28px; position:absolute; right:0; top:0; text-align:center; cursor:pointer; font-size:17px; font-family:Verdana; text-decoration:none; color:gray;}','.PopupDialog-close:hover {color:black;}','.PopupDialog-ft {background-color:#f3f3f3; white-space:nowrap; border-top:1px solid #e0e0e0; padding:5px 5px 5px 0; text-align:right;}','.PopupDialog-bd {padding:20px;}','.PopupDialog-bd-frm {border:none; width:100%}','.PopupDialog-btn {display:inline-block; cursor:pointer; box-shadow:1px 1px #fff; text-shadow: 1px 1px 0 rgba(255, 255, 255, 0.7); background:-moz-linear-gradient(19% 75% 90deg, #E0E0E0, #FAFAFA); background:-webkit-gradient(linear, left top, left bottom, from(#FAFAFA), to(#E0E0E0)); color:#4A4A4A; background-color:white; text-decoration:none; padding:0 15px; height:20px; line-height:20px; text-align:center; border:1px solid #ccd4dc; white-space:nowrap; border-radius:2px}','.PopupDialog-btn:hover {background-color:#eee}','.PopupDialog-btnDefault {}'].join(''),'YSL_WIDGET_POPUP');var GUID=0;var POPUP_COLLECTION=[];var ESC_BINDED=false;var Popup=function(cfg){this.container=null;this.status=0;this._constructReady=Y.emptyFn;this._constructed=false;this.guid='YSL_POPUP_'+(++GUID);this.onShow=Y.emptyFn;this.onClose=Y.emptyFn;this.config=Y.object.extend(true,{ID_PRE:'popup-dialog-id-pre',title:'对话框',content:'测试',width:400,moveEnable:true,moveTriggerByContainer:false,zIndex:1000,isModal:false,topCloseBtn:true,showMask:true,keepWhileHide:false,cssClass:{dialog:'PopupDialog',head:'PopupDialog-hd',body:'PopupDialog-bd',iframe:'PopupDialog-bd-frm',container:'PopupDialog-dom-ctn',foot:'PopupDialog-ft'},buttons:[],sender:Y.emptyFn,reciver:Y.emptyFn},cfg);this.constructStruct();POPUP_COLLECTION.push(this);};Popup.prototype.constructStruct=function(){var _this=this;if(!this.container){this.container=Y.dom.create('div').addClass(this.config.cssClass.dialog);this.container.setStyle('left','-9999px');}
this.container.getDomNode().id=this.config.ID_PRE+Math.random();var content='';if(typeof(this.config.content)=='string'){content='<div class="'+this.config.cssClass.body+'">'+this.config.content+'</div>';}else if(this.config.content.src){content='<iframe allowtransparency="true" guid="'+this.guid+'" src="'+this.config.content.src+'" class="'+this.config.cssClass.iframe+'" frameborder=0></iframe>';}else{content='<div class="'+this.config.cssClass.container+'"></div>';}
var btn_html='';if(this.config.buttons.length>0){var btn_html='<div class="'+this.config.cssClass.foot+'">';for(var i=0;i<this.config.buttons.length;i++){btn_html+='&nbsp;<a href="javascript:;" class="PopupDialog-btn'+(this.config.buttons[i].setDefault?' PopupDialog-btnDefault':'')+'">'+this.config.buttons[i].name+'</a>';}
btn_html+='</div>';}
var html=(['<div class="PopupDialog-wrap">','<div class="PopupDialog-Modal-Mask" style="position:absolute; height:0px; overflow:hidden; z-index:2; background-color:#ccc; width:100%"></div>','<div class="',this.config.cssClass.head+'">','<h3>',this.config.title,'</h3>',(this.config.topCloseBtn?'<a class="PopupDialog-close" href="javascript:;" title="关闭窗口">x</a>':''),'</div>',content,btn_html,'</div>']).join('');this.container.setHtml(html);if(this.config.content.src){this.container.one('iframe').on('load',function(){try{var ifr=this;var w=ifr.contentWindow;var d=w.document;var b=w.document.body;w.focus();}catch(ex){console.log(ex);}
if(!_this.config.height&&b){b.style.overflow='hidden';var info={};if(w.innerWidth){info.visibleHeight=w.innerHeight;}else{var tag=(d.documentElement&&d.documentElement.clientWidth)?d.documentElement:d.body;info.visibleHeight=tag.clientHeight;}
var tag=(d.documentElement&&d.documentElement.scrollWidth)?d.documentElement:d.body;info.documentHeight=Math.max(tag.scrollHeight,info.visibleHeight);ifr.style.height=info.documentHeight+'px';_this.container.setStyle('height','auto');}else{var headRegion=Y.dom.one('.'+_this.config.cssClass.head).getRegion();this.setStyle('height',(_this.config.height-headRegion.height)+'px');}
_this._constructed=true;_this._constructReady();});}else{if(this.config.content.id){Y.dom.one('#'+this.config.content.id).show();this.container.one('div.'+this.config.cssClass.container).getDomNode().appendChild(Y.dom.one('#'+this.config.content.id).getDomNode());}
_this._constructed=true;this._constructReady();}};Popup.prototype.show=function(){var _this=this;if(!this._constructed){this._constructReady=function(){_this.show();};return;}
if(this.config.showMask){Y.widget.masklayer.show();}
this.container.show();var region=Y.object.extend(true,this.container.getRegion(),this.config);region.minHeight=region.minHeight||78;var scroll=YSL.dom.getScroll(),winRegion=YSL.dom.getWindowRegion(),top=left=0;if(winRegion.visibleHeight>region.height){top=scroll.top+(winRegion.visibleHeight-region.height)/4;}else if(winRegion.documentHeight>region.height){top=scroll.top;}
if(winRegion.visibleWidth>region.width){left=winRegion.visibleWidth/2-region.width/2-scroll.left;}else if(winRegion.documentWidth>region.width){left=scroll.left;}
var calStyle=Y.object.extend(true,region,{left:left,top:top,zIndex:this.config.zIndex});this.container.setStyle(calStyle);if(this.config.content.src&&this.config.height){var iframe=this.container.one('iframe');var headRegion=Y.dom.one('.'+this.config.cssClass.head).getRegion();iframe.setStyle('height',(this.config.height-headRegion.height)+'px');}
this.onShow();this.status=1;this.bindEvent();this.bindMoveEvent();this.bindEscCloseEvent();var hasOtherModalPanel=false;var _this=this;Y.lang.each(POPUP_COLLECTION,function(dialog){if(dialog!=_this&&dialog.status&&dialog.config.isModal){_this.config.zIndex=dialog.config.zIndex-1;hasOtherModalPanel=true;return false;}else if(_this!=dialog&&dialog.status&&!dialog.config.isModal){if(dialog.config.zIndex>_this.config.zIndex){_this.config.zIndex=dialog.config.zIndex+1;}else if(dialog.config.zIndex==_this.config.zIndex){_this.config.zIndex+=1;}}});this.container.setStyle('zIndex',this.config.zIndex);if(hasOtherModalPanel){this.setDisable();}else if(_this.config.isModal){Y.lang.each(POPUP_COLLECTION,function(dialog){if(dialog!=_this&&dialog.status){dialog.setDisable();}});this.focus();}else{this.focus();}};Popup.prototype.focus=function(){var a=this.container.one('A');if(a){a.getDomNode().focus();}};Popup.prototype.setEnable=function(){var mask=this.container.one('.PopupDialog-Modal-Mask');if(mask){mask.hide();}};Popup.prototype.setDisable=function(){var size=this.container.getSize();var mask=this.container.one('.PopupDialog-Modal-Mask');mask.setStyle({height:size.height,opacity:0.4});};Popup.prototype.bindEvent=function(){var _this=this;var topCloseBtn=this.container.one('a.PopupDialog-close');if(topCloseBtn){topCloseBtn.getDomNode().onclick=Y.object.bind(this,function(){this.close();});}
this.container.all('a.PopupDialog-btn').each(function(btn,i){btn.on('click',function(){if(_this.config.buttons[i].handler){_this.config.buttons[i].handler.apply(this,arguments);}else{_this.close();}});});var defBtn=this.container.one('a.PopupDialog-btnDefault');if(defBtn){defBtn.getDomNode().focus();}
var _this=this;this.container.on('mousedown',function(){_this.updateZindex();});}
Popup.prototype.updateZindex=function(){var _this=this;var hasModalPanel=false;Y.lang.each(POPUP_COLLECTION,function(dialog){if(dialog!=_this&&dialog.status&&dialog.config.isModal){hasModalPanel=true;return false;}else if(dialog!=_this&&dialog.status){if(dialog.config.zIndex>=_this.config.zIndex){_this.config.zIndex=dialog.config.zIndex+1;}}});if(hasModalPanel){return;}
this.container.setStyle('zIndex',this.config.zIndex);}
Popup.prototype.bindEscCloseEvent=function(){if(ESC_BINDED){return;}
ESC_BINDED=true;var _this=this;Y.event.add(Y.D,'keyup',function(e){if(e.keyCode==Y.event.KEYS.ESC){var lastDialog=null;Y.lang.each(POPUP_COLLECTION,function(dialog){if(dialog.config.isModal&&dialog.status&&dialog.config.topCloseBtn){lastDialog=dialog;return false;}else if(dialog.status&&dialog.config.topCloseBtn){if(!lastDialog||lastDialog.config.zIndex<=dialog.config.zIndex){lastDialog=dialog;}}});if(lastDialog){lastDialog.close();}}});}
Popup.prototype.bindMoveEvent=function(){if(!this.config.moveEnable){return;}
var _this=this;var _lastPoint={X:0,Y:0};var _lastRegion={top:0,left:0};var _moving;Y.event.add(Y.D,'mousemove',function(e){e=e||Y.W.event;if(!_this.container||!_moving||Y.event.getButton(e)!==0){return false;}
offsetX=parseInt(e.clientX-_lastPoint.X,10);offsetY=parseInt(e.clientY-_lastPoint.Y,10);var newLeft=Math.max(_lastRegion.left+offsetX,0);var newTop=Math.max(_lastRegion.top+offsetY,0);_this.container.setStyle({top:newTop,left:newLeft});});Y.event.add(Y.D,'mousedown',function(e){if(!_this.container){return;}
var head=_this.config.moveTriggerByContainer?_this.container:_this.container.one('.'+_this.config.cssClass.head);var tag=Y.dom.one(Y.event.getTarget());if(head.contains(tag)){_moving=true;_lastRegion=_this.container.getRegion();_lastPoint={X:e.clientX,Y:e.clientY};Y.event.preventDefault(e);}});Y.event.add(Y.D,'mouseup',function(){_moving=false;});}
Popup.prototype.close=function(){if(this.onClose()===false){return;}
this.container.hide();this.status=0;var _this=this,hasDialogLeft=false,hasModalPanelLeft=false;if(!this.config.keepWhileHide){var tmp=[];Y.lang.each(POPUP_COLLECTION,function(dialog){if(dialog!=_this){tmp.push(dialog);}});POPUP_COLLECTION=tmp;_this.container.remove();_this.container=null;}
Y.lang.each(POPUP_COLLECTION,function(dialog){if(dialog.status){hasDialogLeft=true;}
if(dialog.status&&dialog.config.isModal){hasModalPanelLeft=true;dialog.setEnable();dialog.focus();return false;}});if(!hasDialogLeft){Y.widget.masklayer.hide();}
if(!hasModalPanelLeft){var _lastTopPanel;Y.lang.each(POPUP_COLLECTION,function(dialog){if(!dialog.status){return;}
dialog.setEnable();if(!_lastTopPanel){_lastTopPanel=dialog;}else if(_lastTopPanel.config.zIndex<=dialog.config.zIndex){_lastTopPanel=dialog;}});if(_lastTopPanel){_lastTopPanel.focus();}}}
Popup.prototype.closeOther=function(){try{var _this=this;Y.lang.each(POPUP_COLLECTION,function(pop){if(pop!=_this){pop.close();}});}catch(e){}};Popup.closeAll=function(){Y.lang.each(POPUP_COLLECTION,function(pop){pop.close();});};Popup.resizeCurrentPopup=function(){if(!Y.W.frameElement){return;}
Y.dom.one(Y.W).on('load',function(){var wr=Y.dom.getWindowRegion();Y.D.body.style.overflow='hidden';Y.W.frameElement.style.height=wr.documentHeight+'px';});};Popup.getPopupByGuid=function(guid){var result;Y.lang.each(POPUP_COLLECTION,function(pop){if(pop.guid==guid){result=pop;return false;}});return result;};Popup.closeCurrentPopup=function(){if(!Y.W.frameElement){return;}
var guid=Y.W.frameElement.getAttribute('guid');if(guid){var pop=parent.YSL.Popup.getPopupByGuid(guid);pop.close();}};Y.widget.Popup=Popup;});(function(Y){Y.widget.slide=function(ctrl,ctn,cfg){var ctn_lst=Y.dom.one(ctn).getChildren();if(ctn_lst.length<2){return false;}
var ctrl_lst=Y.dom.one(ctrl).getChildren(),from_idx=1,tag_idx=2,timer=null,cfg=cfg||{},def_cfg={animate:false,pause_time:2000,cur_cls:'current'};cfg=Y.object.extend(cfg,def_cfg);var static_handler=function(){Y.lang.each(ctn_lst,function(itm){itm.removeClass(cfg.cur_cls);});Y.lang.each(ctrl_lst,function(itm){itm.removeClass(cfg.cur_cls);});ctn_lst[tag_idx-1].addClass(cfg.cur_cls);ctrl_lst[tag_idx-1].addClass(cfg.cur_cls);cur_idx=tag_idx;tag_idx=(tag_idx==ctn_lst.length)?1:(tag_idx+1);};var start=function(){timer=cfg.animate?setInterval(animate_handler,cfg.pause_time,0):setInterval(static_handler,cfg.pause_time,0);};var pause=function(){clearInterval(timer);};void function(){Y.lang.each(ctrl_lst,function(item,idx){item.on('mouseover',function(){tag_idx=(parseInt(idx,10)+1);static_handler();pause();});});Y.lang.each(ctrl_lst,function(item){item.on('mouseout',function(){start();});});}();start();};})(YSL);(function(Y){Y.widget.tab=function(tb,ctn,e,cls){var tbs=Y.dom.one(tb)&&Y.dom.one(tb).getChildren(),ctns=Y.dom.one(ctn)&&Y.dom.one(ctn).getChildren(),e=e?e:'mouseover',cls=cls?cls:'current';Y.lang.each(tbs,function(obj,idx){obj.on(e,function(){Y.lang.each(tbs,function(obj,j){j==idx?obj.addClass(cls):obj.removeClass(cls);});Y.lang.each(ctns,function(obj,j){j==idx?obj.addClass(cls):obj.removeClass(cls);});});});};})(YSL);(function(Y){var TIP_CONTAINER=null;var Tip=function(arg1,wtype,time,closeCalllback){this.container=TIP_CONTAINER;var cfg=arg1;if(typeof(arg1)=='string'){cfg={'msg':arg1,'type':wtype||0,'time':(time>0?time*1000:2000)};}
this.config=Y.object.extend({'msg':'','type':0,'time':2000,'auto':true,'callback':closeCalllback},cfg);if(this.config.auto){this.show();if(this.config.time){setTimeout(Y.object.bind(this,function(){this.hide();}),this.config.time);}}};Tip.prototype.show=function(){if(!this.container){this.container=TIP_CONTAINER=Y.dom.create('div').addClass('ysl-tip-container-wrap');}
var html=(['<span class="ysl-tip-container">','<span class="ysl-tip-icon-',this.config.type,'"></span>','<span class="ysl-tip-content">',this.config.msg,'</span>','</div>']).join('');if(Y.ua.ie6){var viewP=Y.dom.getWindowRegion();this.container.setStyle('top',viewP.visibleHeight/2+viewP.verticalScroll);}
this.container.setHtml(html).show();};Tip.prototype.hide=function(){if(this.container){this.container.hide();this.config.callback&&this.config.callback(this);}};Tip.closeAll=function(){if(TIP_CONTAINER){TIP_CONTAINER.hide();}}
Tip.prototype.destory=function(){this.container.remove();};Y.widget.Tip=Tip;})(YSL);(function(Y){var Tween={Linear:function(t,b,c,d){return c*t/d+b;},Quad:{easeIn:function(t,b,c,d){return c*(t/=d)*t+b;},easeOut:function(t,b,c,d){return-c*(t/=d)*(t-2)+b;},easeInOut:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t+b;return-c/2*((--t)*(t-2)-1)+b;}},Cubic:{easeIn:function(t,b,c,d){return c*(t/=d)*t*t+b;},easeOut:function(t,b,c,d){return c*((t=t/d-1)*t*t+1)+b;},easeInOut:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t+b;return c/2*((t-=2)*t*t+2)+b;}},Quart:{easeIn:function(t,b,c,d){return c*(t/=d)*t*t*t+b;},easeOut:function(t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b;},easeInOut:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t+b;return-c/2*((t-=2)*t*t*t-2)+b;}},Quint:{easeIn:function(t,b,c,d){return c*(t/=d)*t*t*t*t+b;},easeOut:function(t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;},easeInOut:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t*t+b;return c/2*((t-=2)*t*t*t*t+2)+b;}},Sine:{easeIn:function(t,b,c,d){return-c*Math.cos(t/d*(Math.PI/2))+c+b;},easeOut:function(t,b,c,d){return c*Math.sin(t/d*(Math.PI/2))+b;},easeInOut:function(t,b,c,d){return-c/2*(Math.cos(Math.PI*t/d)-1)+b;}},Expo:{easeIn:function(t,b,c,d){return(t==0)?b:c*Math.pow(2,10*(t/d-1))+b;},easeOut:function(t,b,c,d){return(t==d)?b+c:c*(-Math.pow(2,-10*t/d)+1)+b;},easeInOut:function(t,b,c,d){if(t==0)return b;if(t==d)return b+c;if((t/=d/2)<1)return c/2*Math.pow(2,10*(t-1))+b;return c/2*(-Math.pow(2,-10*--t)+2)+b;}},Circ:{easeIn:function(t,b,c,d){return-c*(Math.sqrt(1-(t/=d)*t)-1)+b;},easeOut:function(t,b,c,d){return c*Math.sqrt(1-(t=t/d-1)*t)+b;},easeInOut:function(t,b,c,d){if((t/=d/2)<1)return-c/2*(Math.sqrt(1-t*t)-1)+b;return c/2*(Math.sqrt(1-(t-=2)*t)+1)+b;}},Elastic:{easeIn:function(t,b,c,d,a,p){if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(!a||a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},easeOut:function(t,b,c,d,a,p){if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(!a||a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return(a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b);},easeInOut:function(t,b,c,d,a,p){if(t==0)return b;if((t/=d/2)==2)return b+c;if(!p)p=d*(.3*1.5);if(!a||a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);if(t<1)return-.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*.5+c+b;}},Back:{easeIn:function(t,b,c,d,s){if(s==undefined)s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b;},easeOut:function(t,b,c,d,s){if(s==undefined)s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},easeInOut:function(t,b,c,d,s){if(s==undefined)s=1.70158;if((t/=d/2)<1)return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;}},Bounce:{easeIn:function(t,b,c,d){return c-Tween.Bounce.easeOut(d-t,0,c,d)+b;},easeOut:function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+.75)+b;}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+.9375)+b;}else{return c*(7.5625*(t-=(2.625/2.75))*t+.984375)+b;}},easeInOut:function(t,b,c,d){if(t<d/2)return Tween.Bounce.easeIn(t*2,0,c,d)*.5+b;else return Tween.Bounce.easeOut(t*2-d,0,c,d)*.5+c*.5+b;}}};Y.widget.Tween=Tween;})(YSL);(function(Y){var REGEXP_COLLECTION={REQUIRE:/^.+$/,CHINESE_ID:/^\d{14}(\d{1}|\d{4}|(\d{3}[xX]))$/,PHONE:/^[0-9]{7,13}$/,EMAIL:/^[\w-]+(\.[\w-]+)*@[\w-]+(\.[\w-]+)+$/,POSTCODE:/^[0-9]{6}$/,AREACODE:/^0[1-2][0-9]$|^0[1-9][0-9]{2}$/,CT_PASSPORT:/^[0-9a-zA-Z]{5,40}$/,CT_MOBILE:/^(13|15|18)[0-9]{9}$/,QQ:/^\d{5,13}$/,TRIM:/^\s+|\s+$/g};var Validator=function(config){this.config=Y.object.extend(true,{form:'#frm',rules:{},checkAllRules:false,breakOnError:false,onAllCheckPass:function(){return true;},onCheckPass:function(item){var pn=Y.dom.one(item.parentNode);var span=pn.one('span.msg')||pn.create('span').addClass('msg');span.addClass('pass').removeClass('error').setHtml('ok');},onError:function(item,errs){var err=errs[0];var pn=Y.dom.one(item.parentNode);var span=pn.one('span.msg')||pn.create('span').addClass('msg');span.addClass('error').removeClass('pass').setHtml(err);},resetError:function(form){Y.dom.one(form).all('span.msg').each(function(span){span.removeClass('pass').removeClass('error');span.setHtml('')});}},config);this.elements=[];this.errors={};if(!this.config.form||!this.config.rules){throw('validate need form & rules');}
this.init();};Validator.prototype.init=function(){var _this=this;this.elements=Y.dom.one(this.config.form).getDomNode().elements;Y.dom.one(this.config.form).on('submit',function(){_this.errors={};_this.config.resetError(_this.config.form);var errorList=_this.checkAll();if(!errorList||Y.lang.isEmptyObject(errorList)){return _this.config.onAllCheckPass();}else{Y.event.preventDefault();return false;}});};Validator.prototype.checkAll=function(){for(var i=0;i<this.elements.length;i++){var element=this.elements[i],name=this.elements[i].name;if(this.checkElementCompitable(element)){if(element.type=='radio'&&this.errors[element.name]){continue;}
var errs=this.checkItem(element,this.config.rules[name],this.config.checkAllRules);if(errs){this.errors[name]=errs;this.config.onError(element,errs);if(this.config.breakOnError){return;}}else{this.config.onCheckPass(element);}}}
return this.errors;};Validator.prototype.checkElementCompitable=function(element){return element.tagName!='FIELDSET'&&element.type!='hidden'&&element.type!='submit'&&element.type!='button'&&element.type!='reset'&&element.type!='image';}
Validator.prototype.checkItem=function(element,rules,checkAllRules){if(!rules){return null;}
var errors=[],name=element.name;if(element.tagName=='SELECT'||(element.tagName=='INPUT'&&(element.type=='text'||element.type=='password'))){var val=element.value.replace(REGEXP_COLLECTION.TRIM,'');for(var key in rules){var uKey=key.toUpperCase();if(REGEXP_COLLECTION[uKey]){if(!REGEXP_COLLECTION[uKey].test(val)){if(!checkAllRules){return[rules[key]];}else{errors.push(rules[key]);}}}
else if(uKey.indexOf('MAX')===0){var len=parseInt(uKey.substr(3),10);if(len>0&&len<val.length){if(!checkAllRules){return[rules[key]];}else{errors.push(rules[key]);}}}
else if(uKey.indexOf('MIN')===0){var len=parseInt(uKey.substr(3),10);if(len>0&&len>val.length){if(!checkAllRules){return[rules[key]];}else{errors.push(rules[key]);}}}
else if(uKey.indexOf('/')===0){var reg=new RegExp(key);if(!reg.test(val)){if(!checkAllRules){return[rules[key]];}else{errors.push(rules[key]);}}}
else if(typeof(rules[key])=='function'){var ret=rules[key](val);if(ret){if(!checkAllRules){return[ret];}else{errors.push(ret);}}}}}
else if(element.type=='checkbox'){for(var key in rules){var uKey=key.toUpperCase();if(uKey=='REQUIRE'){if(!element.checked){return[rules[key]];}else{return null;}}}}
else if(element.type=='radio'){for(var key in rules){var uKey=key.toUpperCase();if(uKey=='REQUIRE'){if(!this.checkRadioChecked(element.name)){return[rules[key]];}else{return null;}}}}
return errors.length?errors:null;};Validator.prototype.checkRadioChecked=function(name){for(var i=0;i<this.elements.length;i++){if(this.elements[i].name==name&&!!this.elements[i].checked){return true;}}
return false;}
Y.widget.Validator=Validator;})(YSL);